// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_hello
List rcpp_hello();
RcppExport SEXP _RadixSort_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_countingSort
IntegerVector rcpp_countingSort(IntegerVector arr, int position);
RcppExport SEXP _RadixSort_rcpp_countingSort(SEXP arrSEXP, SEXP positionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< int >::type position(positionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_countingSort(arr, position));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_RadixSort
IntegerVector rcpp_RadixSort(IntegerVector arr);
RcppExport SEXP _RadixSort_rcpp_RadixSort(SEXP arrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type arr(arrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_RadixSort(arr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fusion
NumericVector rcpp_fusion(NumericVector gauche, NumericVector droite);
RcppExport SEXP _RadixSort_rcpp_fusion(SEXP gaucheSEXP, SEXP droiteSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type gauche(gaucheSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type droite(droiteSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fusion(gauche, droite));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_TriFusion
NumericVector rcpp_TriFusion(NumericVector tableau);
RcppExport SEXP _RadixSort_rcpp_TriFusion(SEXP tableauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tableau(tableauSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_TriFusion(tableau));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RadixSort_rcpp_hello", (DL_FUNC) &_RadixSort_rcpp_hello, 0},
    {"_RadixSort_rcpp_countingSort", (DL_FUNC) &_RadixSort_rcpp_countingSort, 2},
    {"_RadixSort_rcpp_RadixSort", (DL_FUNC) &_RadixSort_rcpp_RadixSort, 1},
    {"_RadixSort_rcpp_fusion", (DL_FUNC) &_RadixSort_rcpp_fusion, 2},
    {"_RadixSort_rcpp_TriFusion", (DL_FUNC) &_RadixSort_rcpp_TriFusion, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RadixSort(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
