// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_hello
List rcpp_hello();
RcppExport SEXP _RadixSort_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}
// countingSortAlgo
IntegerVector countingSortAlgo(IntegerVector arr, int position);
RcppExport SEXP _RadixSort_countingSortAlgo(SEXP arrSEXP, SEXP positionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< int >::type position(positionSEXP);
    rcpp_result_gen = Rcpp::wrap(countingSortAlgo(arr, position));
    return rcpp_result_gen;
END_RCPP
}
// radixSortAlgo_c
IntegerVector radixSortAlgo_c(IntegerVector arr);
RcppExport SEXP _RadixSort_radixSortAlgo_c(SEXP arrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type arr(arrSEXP);
    rcpp_result_gen = Rcpp::wrap(radixSortAlgo_c(arr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RadixSort_rcpp_hello", (DL_FUNC) &_RadixSort_rcpp_hello, 0},
    {"_RadixSort_countingSortAlgo", (DL_FUNC) &_RadixSort_countingSortAlgo, 2},
    {"_RadixSort_radixSortAlgo_c", (DL_FUNC) &_RadixSort_radixSortAlgo_c, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RadixSort(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
