# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call(`_RadixSort_rcpp_hello`)
}

rcpp_countingSort <- function(arr, position) {
    .Call(`_RadixSort_rcpp_countingSort`, arr, position)
}

rcpp_RadixSort <- function(arr) {
    .Call(`_RadixSort_rcpp_RadixSort`, arr)
}

rcpp_fusion <- function(gauche, droite) {
    .Call(`_RadixSort_rcpp_fusion`, gauche, droite)
}

rcpp_TriFusion <- function(tableau) {
    .Call(`_RadixSort_rcpp_TriFusion`, tableau)
}

