# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call(`_RadixSort_rcpp_hello`)
}

countingSortAlgoRcpp <- function(arr, position) {
    .Call(`_RadixSort_countingSortAlgoRcpp`, arr, position)
}

radixSortAlgoRcpp <- function(arr) {
    .Call(`_RadixSort_radixSortAlgoRcpp`, arr)
}

fusionRcpp <- function(gauche, droite) {
    .Call(`_RadixSort_fusionRcpp`, gauche, droite)
}

triFusionRcpp <- function(tableau) {
    .Call(`_RadixSort_triFusionRcpp`, tableau)
}

